### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by trentbraidner** [Zaddish/KillTheDJ#1]
<img width="268" alt="image" src="https://github.com/Zaddish/KillTheDJ/assets/17211252/d921de35-08b7-48a6-9109-838455a9fc96">

As per the log output tracks in another language dont display

![image](https://github.com/Zaddish/KillTheDJ/assets/17211252/8ff818c9-7a1e-4640-a6ae-dd69664007a8)

**Comment by Zaddish** [comment]
fixed in: 19be502
